window.WIKI_LANG = {
  pt: {
    'brand.rocha': 'Rocha',
    'brand.project': 'Project',
    'nav.home': 'Inicio',
    'nav.projects': 'Projetos',
    'nav.downloads': 'Downloads',
    'nav.wiki': 'Wiki',
    'nav.community': 'Comunidade',
    'account.login': 'Entrar',
    'hero.eyebrow': 'Wiki Rocha Project',
    'hero.title': 'Documentacao dos projetos',
    'hero.subtitle': 'Escolha um projeto para abrir o manual. A ideia aqui e ser rapido: nada de parede de texto logo de cara.',
    'content.manualTitle': 'Manual do plugin',
    'content.manualText': 'Os topicos ficam recolhidos para a pagina nao virar uma parede de texto. Use a lateral ou abra pelo sinal de +.',
    'section.install': 'Instalacao',
    'section.permissions': 'Permissoes base',
    'section.panel': 'Painel web do servidor',
    'section.modules': 'Modulos disponiveis',
    'section.extraSystems': 'Sistemas adicionais',
    'section.commands': 'Referencia completa de comandos',
    'section.login': 'Login e AuraClient',
    'section.discord': 'Discord',
    'section.shop': 'Loja',
    'section.missions': 'Missoes',
    'section.vip': 'VIP e cargos',
    'section.prefix': 'Prefix visual e glyphs',
    'section.npc': 'NPC',
    'section.hologram': 'Texto flutuante',
    'section.cla': 'Cla',
    'section.claim': 'Terreno',
    'section.protection': 'Protecao',
    'section.rules': 'Regras e ajuda',
    'section.teleport': 'Teleporte',
    'section.pvp': 'PvP, duelo e combat log',
    'section.border': 'Border e bloqueios',
    'section.utilities': 'Utilidades',
    'section.troubleshooting': 'Problemas comuns',
    'sidebar.allWikis': 'Todas as wikis',
    'sidebar.project': 'AuraEssentials',
    'project.plugin': 'Plugin',
    'project.launcher': 'Launcher',
    'project.client': 'Client',
    'project.pluginDesc': 'Instalacao, painel web, modulos, comandos e configuracao.',
    'project.launcherDesc': 'Launcher Java/Bedrock, sessoes e downloads.',
    'project.clientDesc': 'Cliente, mod, cosmeticos e integracao com servidor.',
    'install.serverTitle': 'Servidor recomendado',
    'install.serverText': 'Use Paper, Purpur ou Pufferfish na linha 1.21.9+. O plugin foi feito para rodar como plugin Bukkit/Paper normal, sem proxy obrigatorio.',
    'install.optTitle': 'Dependencias opcionais',
    'install.optText': 'Geyser/Floodgate sao softdepend. Se estiverem presentes, o menu Bedrock e forms administrativos ficam mais naturais para jogadores Bedrock.',
    'install.tip': 'O plugin foi feito para rodar como plugin Bukkit/Paper normal, sem proxy obrigatório.',
    'panel.title': 'Painel web do servidor',
    'panel.text': 'O painel web edita um rascunho seguro. Nada e aplicado direto no servidor enquanto um admin nao confirmar dentro do jogo.',
    'panel.explain': 'O painel web edita um rascunho seguro. Nada e aplicado direto no servidor enquanto um admin nao confirmar dentro do jogo.',
    'panel.afterLink': 'Depois de vincular o servidor na sua conta Rocha, ele aparece em Perfil > Servidor Aura. O link temporario expira em ate 30 minutos.',
    'panel.security': 'A sessao e criada apenas para administradores. O plugin envia um snapshot, o site salva um rascunho e o servidor so aplica depois de <code>/aurapainel aplicar</code>.',
    'panel.step1': 'Gere a sessao',
    'panel.step2': 'Edite no site',
    'panel.step3': 'Salve o rascunho',
    'panel.step4': 'Confirme no jogo',
    'permissions.explain': 'Lista principal de permissões do plugin para administração, login, terrenos, teleporte, VIP e moderação.',
    'permissions.admin': 'Administra o plugin, abre painel, muda sistemas, NPC, holograma, economia, cargos e servidor. (padrao: OP)',
    'permissions.rapidLogin': 'Permite usar /rapidologin para autenticar jogador rapidamente. (padrao: OP)',
    'permissions.graveto': 'Permite pegar o graveto de captura com /graveto. (padrao: todos)',
    'permissions.gravetoUse': 'Permite usar o graveto nos mobs liberados. (padrao: todos)',
    'permissions.terreno': 'Permite usar /terreno; o servidor ainda pode exigir VIP. (padrao: todos)',
    'permissions.vincular': 'Permite usar /vincular para conectar Discord. (padrao: todos)',
    'permissions.autopickup': 'Permite alternar AutoPickup pessoal. (padrao: todos)',
    'permissions.cla': 'Permite usar o sistema de cla. (padrao: todos)',
    'permissions.rtp': 'Permite /rtp. (padrao: todos)',
    'permissions.rtpBypass': 'Ignora cooldown do RTP. (padrao: OP)',
    'permissions.inspect': 'Permite /verinv e /verender. (padrao: OP)',
    'permissions.vanish': 'Permite /vanish. (padrao: OP)',
    'permissions.vanishSee': 'Permite ver jogadores que estao em vanish. (padrao: OP)',
    'permissions.claCreate': 'Permite criar um cla. (padrao: todos)',
    'permissions.servers': 'Permite abrir a lista de servidores para transferencia. (padrao: todos)',
    'permissions.auction': 'Permite usar o leilao entre jogadores. (padrao: todos)',
    'permissions.fly': 'Permite usar /fly. (padrao: OP)',
    'permissions.gamemode': 'Permite usar /gm. (padrao: OP)',
    'permissions.setspawn': 'Permite definir o spawn do lobby. (padrao: OP)',
    'permissions.timefreeze': 'Permite usar /congelar e /freezy. (padrao: OP)',
    'permissions.proxyportal': 'Permite criar e remover portais proxy customizados. (padrao: OP)',
    'permissions.caixaAdmin': 'Permite administrar Caixas e Chaves. (padrao: OP)',
    'permissions.maintenanceAdmin': 'Permite administrar o modo manutencao. (padrao: OP)',
    'permissions.maintenanceBypass': 'Ignora o redirecionamento do modo manutencao. (padrao: OP)',
    'permissions.nick': 'Permite usar /mudarnick sem depender de VIP. (padrao: nenhum)',
    'permissions.chatGlobal': 'Permite usar /g quando o global estiver bloqueado para membros. (padrao: OP)',
    'permissions.chatGlobalBypass': 'Ignora bloqueio e cooldown do chat global. (padrao: OP)',
    'permissions.shopChestCreate': 'Permite criar lojas de bau. (padrao: todos)',
    'permissions.shopChestUse': 'Permite comprar e vender em lojas de bau. (padrao: todos)',
    'permissions.shopChestAdmin': 'Permite proteger e remover lojas de bau. (padrao: OP)',
    'modules.title': 'Modulos disponiveis',
    'modules.text': 'Cada modulo pode ser ligado/desligado em modules.enabled, pelo painel em Configurar ou por /aurasetup toggle <modulo>.',
    'modules.explain': 'Cada modulo pode ser ligado/desligado em modules.enabled, pelo painel em Configurar ou por /aurasetup toggle <modulo>.',
    'login.title': 'Login e AuraClient',
    'login.text': 'Sistema de registro local para servidor offline/online misto, com senha, troca de senha, controle de sessao e protecao contra multiconta.',
    'login.explain': 'Sistema de registro local para servidor offline/online misto, com senha, troca de senha, controle de sessao e protecoes contra multiconta.',
    'login.config': 'Configuracoes principais: <code>enableIpTrust</code>, <code>trustedDurationSeconds</code>, <code>multiAccount</code>, <code>modGate.requireAuraClient</code>, <code>authRouting</code> e packs Java/Bedrock.',
    'login.registrar': 'Cria a senha do jogador.',
    'login.entrar': 'Autentica a sessao atual.',
    'login.mudarsenha': 'Troca a senha da conta.',
    'login.rapidlogin': 'Admin autentica um jogador manualmente.',
    'login.multiconta': 'Admin controla limite de contas por IP.',
    'discord.title': 'Discord',
    'discord.text': 'Integra vinculo de conta, bridge e exigencia de Discord. O token do bot fica no servidor, nunca no site publico.',
    'discord.explain': 'Integra vinculo de conta, bridge e exigencia de Discord. O token do bot fica no servidor, nunca no site publico.',
    'discord.config': 'Campos importantes: <code>discordLink.botToken</code>, <code>controlChannelId</code>, <code>forceOnJoin</code>, <code>requiredAfterHours</code> e <code>useOriginalServerText</code>.',
    'discord.vincular': 'Gera codigo para vincular Minecraft ao Discord.',
    'discord.vincularCodigo': 'Consome codigo recebido pelo fluxo do bot.',
    'discord.desvincular': 'Admin remove vinculo de um jogador.',
    'discord.channels': 'Use <code>chatChannelId</code> para o canal publico de bridge e <code>controlChannelId</code> para o canal privado de controle entre bots. <code>forceOnJoin</code> e <code>requiredAfterHoursEnabled</code> podem exigir vinculo no login.',
    'shop.title': 'Loja',
    'shop.text': 'Menu de compra/venda com categorias, produtos, icone por item Minecraft, valor de compra, valor de venda e moeda configuravel.',
    'shop.explain': 'Menu de compra/venda com categorias, produtos, icone por item Minecraft, valor de compra, valor de venda e moeda configuravel.',
    'shop.file': 'Arquivo principal: <code>shop.yml</code>. Pelo painel, use Loja > Catalogo para revisar e Loja > Editar produtos para adicionar/remover itens.',
    'shop.abre': 'Abre a loja.',
    'shop.comando': 'Usa loja por comando quando GUI nao for ideal.',
    'shop.admin': 'Administra valores por comando.',
    'shop.sellOptions': 'Vende uma quantidade ou tudo quando usar o argumento <code>all</code>.',
    'shop.englishAliases': 'Aliases EN aceitos pelo executor da loja.',
    'missions.title': 'Missoes',
    'missions.text': 'Missoes com categorias e objetivos de matar mobs, minerar blocos ou colher plantacoes. O jogador ativa uma missao, progride e pode cancelar.',
    'missions.explain': 'Missoes com categorias e objetivos de matar mobs, minerar blocos ou colher plantacoes. O jogador ativa uma missao, progride e pode cancelar.',
    'missions.file': 'Arquivo principal: <code>missions.yml</code>. Configuracoes: <code>missions.autosaveSeconds</code> e <code>missions.repeatCooldownSeconds</code>.',
    'missions.abre': 'Abre o menu de missoes.',
    'missions.ativar': 'Ativa uma missao por ID.',
    'missions.listar': 'Lista missoes carregadas.',
    'missions.cancelar': 'Cancela missao ativa e remove progresso.',
    'missions.categories': 'Categorias atuais incluem <code>mining</code> e <code>farming</code>; use <code>/quest activate</code> e <code>/quest list</code> como aliases EN.',
    'vip.title': 'VIP e cargos',
    'vip.text': 'Controla VIPs, cargos visuais, chaves de ativacao, kit VIP e utilidades como bau, craft, bigorna e topo.',
    'vip.explain': 'Controla VIPs, cargos visuais, chaves de ativacao, kit VIP e utilidades como bau, craft, bigorna e topo.',
    'vip.config': 'No painel, VIPs podem ter itens, quantidade, lore, nome customizado, brilho, inquebravel e encantamentos Vanilla/NBT.',
    'vip.setvip': 'Define ou remove VIP.',
    'vip.entregarcargo': 'Define cargo visual especial.',
    'vip.gerarchave': 'Cria chave de uso unico.',
    'vip.chave': 'Ativa uma chave VIP.',
    'vip.kitvip': 'Entrega kit do VIP.',
    'vip.resetkitvip': 'Libera novo uso do kit VIP.',
    'vip.behavior': 'O kit VIP e de uso unico por VIP quando <code>vipKit.singleUsePerVip</code> esta ativo; <code>/resetkitvip</code> libera novo uso.',
    'prefix.title': 'Prefix visual e glyphs',
    'prefix.text': 'O plugin separa visual de chat, nametag e tablist. Os glyphs dependem do resource pack Java/Bedrock para aparecerem corretos.',
    'prefix.explain': 'O plugin separa visual de chat, nametag e tablist. Os glyphs dependem do resource pack Java/Bedrock para aparecerem corretos.',
    'prefix.help': 'Use codigos Minecraft como <code>&amp;6&amp;l</code> nos campos que aceitam texto formatado. O painel renderiza previa com a formatacao basica.',
    'prefix.chatMessage': '<code>chat_message</code>: formato das mensagens no chat.',
    'prefix.nametagPlayer': '<code>nametag_player</code>: texto acima da cabeca.',
    'prefix.tablist': '<code>tablist</code>: visual na lista de jogadores.',
    'npc.title': 'NPC',
    'npc.text': 'NPCs do servidor com skin, titulo, descricao, acao e posicao. Podem abrir menu, TPA, loja, missoes ou executar comando configurado.',
    'npc.explain': 'NPCs do servidor com skin, titulo, descricao, acao e posicao. Podem abrir menu, TPA, loja, missoes ou executar comando configurado.',
    'npc.config': 'Config global: <code>npc.renderDistanceChunks</code> e <code>npc.hologramOffsetY</code>.',
    'npc.currentConfig': 'Valores atuais: renderiza a 1 chunk e usa offset de holograma 2.05. As skins nomeadas ficam em <code>npc_visuals.yml</code>.',
    'hologram.title': 'Texto flutuante',
    'hologram.text': 'Hologramas simples para avisos, lobby, lojas e areas do servidor.',
    'hologram.explain': 'Hologramas simples para avisos, lobby, lojas e areas do servidor.',
    'hologram.config': 'Config global: <code>holograma.renderDistanceChunks</code>, <code>backgroundEnabled</code> e <code>lineWidth</code>.',
    'hologram.currentConfig': 'Valores atuais: renderiza a 1 chunk, fundo ligado e largura de linha 220.',
    'cla.title': 'Cla',
    'cla.text': 'Sistema de grupo de jogadores com tag, nome, descricao, cor, membros, subdonos, base, warps, banco, chat, aliancas e PvP interno.',
    'cla.explain': 'Sistema de grupo de jogadores com tag, nome, descricao, cor, membros, subdonos, base, warps, banco, chat, aliancas e PvP interno.',
    'cla.config': 'Config principal: tamanho de tag/nome, maximo de membros, warps, banco, aliancas, PvP interno e auto delete quando so resta dono.',
    'cla.currentConfig': 'Valores atuais: tag 2-5 caracteres, nome 3-16, descricao ate 60, 10 membros, 2 subdonos, 1 warp, convite por 300s e auto-delete apos 10h somente com o dono. Aliancas, PvP interno, Ender Chest, warp extra, cargos e banco estao habilitados.',
    'claim.title': 'Terreno',
    'claim.text': 'Claim de chunk 16x16. O jogador pega uma pa de terreno e registra o chunk clicando em um bloco. Por padrao pode exigir VIP.',
    'claim.explain': 'Claim de chunk 16x16. O jogador pega uma pa de terreno e registra o chunk clicando em um bloco. Por padrao pode exigir VIP.',
    'claim.pega': 'Pega a pa de claim.',
    'claim.permitir': 'Autoriza outro jogador no terreno.',
    'claim.remover': 'Remove permissao.',
    'claim.listar': 'Mostra terrenos.',
    'claim.ver': 'Mostra borda do chunk atual.',
    'claim.deletar': 'Remove claim proprio ou de outro como admin.',
    'claim.currentConfig': 'Config atual: VIP e obrigatorio; limite de 4096 blocos para membro, 16384 para VIP e 262144 para admin. O limite VIP e separado do limite comum.',
    'protection.title': 'Protecao',
    'protection.text': 'Areas administrativas por selecao de duas posicoes. Serve para spawn, lojas, arenas ou regioes especiais.',
    'protection.explain': 'Areas administrativas por selecao de duas posicoes. Serve para spawn, lojas, arenas ou regioes especiais.',
    'protection.flags': 'As flags aceitas incluem break, place, interact, buckets, entry, monsters, pvp, entity_damage e explosions. A area pode ser criada com duas posicoes e administrada pelo painel ou comando.',
    'rules.title': 'Regras e ajuda',
    'rules.text': 'Dois textos simples para orientar jogador dentro do servidor. Aceitam codigos de cor Minecraft e link de wiki.',
    'rules.explain': 'Dois textos simples para orientar jogador dentro do servidor. Aceitam codigos de cor Minecraft e link de wiki.',
    'rules.config': 'Campos principais: <code>texts.regrasTitle</code>, <code>texts.regras</code>, <code>texts.regrasWikiUrl</code>, <code>texts.ajudaTitle</code>, <code>texts.ajuda</code> e <code>texts.ajudaWikiUrl</code>.',
    'rules.regras': 'Mostra titulo, linhas de regras e link configurado.',
    'rules.ajuda': 'Mostra comandos basicos, instrucoes de login e link configurado.',
    'utilities.menuMain': 'Menu principal Bedrock/Geyser.',
    'utilities.menuAdmin': 'Menu administrativo Bedrock.',
    'utilities.kit': 'Kit inicial de uso unico.',
    'utilities.saldo': 'Mostra saldo.',
    'utilities.dinheiro': 'Admin altera saldo.',
    'utilities.pix': 'Transfere moedas.',
    'utilities.clearlag': 'Limpa drops configurados.',
    'utilities.graveto': 'Recebe item de captura de mobs liberados.',
    'utilities.autopickup': 'Controla coleta automatica.',
    'utilities.skin': 'Define skin oficial por nick.',
    'utilities.vanish': 'Invisibilidade para staff.',
    'utilities.inspect': 'Inspecao de inventario e ender chest.',
    'utilities.currentConfig': 'AutoPickup esta ativo por padrao para blocos, mobs e pesca; o jogador pode alternar e recebe aviso de inventario cheio. ClearLag roda a cada 600s, remove drops com pelo menos 30s, ignora itens com nome customizado e avisa em 60s e 5s.',
    'teleport.title': 'Teleporte',
    'teleport.text': 'TPA, back, warps, homes e RTP com cooldown, guardas de dimensao e radius seguros.',
    'teleport.tpaTitle': 'TPA e Back',
    'teleport.tpaText': '<code>/tpa &lt;player&gt;</code>, <code>/aceitar &lt;player&gt;</code>, <code>/negar &lt;player&gt;</code> e <code>/back</code>. Pode bloquear por dimensao.',
    'teleport.warpTitle': 'Warp, Home e RTP',
    'teleport.warpText': '<code>/setwarp</code>, <code>/warp</code>, <code>/sethome</code>, <code>/home</code>, <code>/delhome</code> e <code>/rtp</code>. RTP respeita raio, cooldown, world border e agua/lava.',
    'teleport.currentConfig': 'Config atual: RTP tem cooldown de 300s, warmup de 3s, raio de 250 a 5000, ate 24 tentativas e esta habilitado apenas no Overworld por padrao. TPA e Back estao habilitados no Overworld, Nether e End.',
    'pvp.title': 'PvP, duelo e combat log',
    'pvp.text': 'Sistemas de PvP personalizado, duelos e combat log com protecoes de saida e bloqueios em combate.',
    'pvp.explain': 'Sistemas de PvP personalizado, duelos e combat log com protecoes de saida e bloqueios em combate.',
    'pvp.config': 'CombatLog pode bloquear warp, tpa, rtp, home e back durante combate. Tambem pode matar ao sair, se configurado.',
    'pvp.status': 'Jogador muda estado pessoal de PvP.',
    'pvp.admin': 'Admin controla PvP por dimensao.',
    'pvp.duelo': 'Cria desafio PvP em arena temporaria.',
    'pvp.currentConfig': 'Config atual: combate dura 8s; bloqueia warp, TPA, RTP, home, back e base do cla; mostra actionbar e nao mata ao sair por padrao. Duelo aceita as tres dimensoes, com convite de 30s, pronto de 45s e countdown de 3s.',
    'border.title': 'Border e bloqueios',
    'border.text': 'Sistema de world border global e lista de itens bloqueados por modulo ou painel.',
    'border.globalTitle': 'Border Global',
    'border.globalText': 'Define tamanho e centro de world border para Overworld, Nether e End. Pode ser ativado pelo modulo <code>border</code>.',
    'border.globalCommand': 'Comando rapido: <code>/setborder &lt;tamanho&gt;</code> usa sua posicao atual como centro no mundo em que voce esta.',
    'border.blockedTitle': 'Itens Bloqueados',
    'border.blockedText': 'Remove materiais proibidos do inventario e pode verificar Ender Chest. Configure em <code>blockedItems.materials</code> ou pelo painel em Itens bloqueados.',
    'border.blockedTip': 'Use para bloquear command block, bedrock, barreiras ou qualquer material que nao deve circular.',
    'border.currentConfig': 'Por padrao, o modulo border e itens bloqueados comecam desativados. A border inicial e 8000 no Overworld, 5000 no Nether e 12000 no End; itens bloqueados verificam tambem Ender Chest quando ativados.',
    'utilities.title': 'Utilidades',
    'utilities.text': 'Menu, kits, saldo, pix, clearlag, graveto, autopickup, skin, vanish e inspeccao.',
    'utilities.explain': 'Menu, kits, saldo, pix, clearlag, graveto, autopickup, skin, vanish e inspeccao para o dia a dia do jogador.',
    'troubleshooting.title': 'Problemas comuns',
    'troubleshooting.text': 'Checklist rapido para os erros mais frequentes de glyphs, comandos, painel e login.',
    'troubleshooting.explain': 'Checklist rapido para os erros mais frequentes de glyphs, comandos, painel e login.',
    'troubleshooting.glyphsTitle': 'Glyphs aparecem quadrados ou pequenos',
    'troubleshooting.glyphsText': 'O jogador nao carregou o resource pack correto. Confira <code>javaResourcePack</code>, <code>bedrockResourcePack</code> e se o servidor exige o pack.',
    'troubleshooting.commandTitle': 'Comando nao aparece no tab',
    'troubleshooting.commandText': 'Confira se o modulo esta ativo em <code>modules.enabled</code> ou no painel Configurar. Depois use <code>/aurasetup reload</code> e peça para o jogador relogar se necessario.',
    'troubleshooting.siteTitle': 'Alterei no site e nao mudou no servidor',
    'troubleshooting.siteText': 'Salvar no site cria rascunho. Entre no servidor e use <code>/aurapainel alteracoes</code> e depois <code>/aurapainel aplicar</code>.',
    'troubleshooting.discordTitle': 'Discord envia jogo para Discord, mas nao volta',
    'troubleshooting.discordText': 'Revise <code>discordLink.botToken</code>, <code>controlChannelId</code>, permissoes do bot no canal e se o modulo Discord esta ativo.',
    'troubleshooting.loginTitle': 'Jogador nao consegue entrar',
    'troubleshooting.loginText': 'Confira Login, Multiconta, AuthRouting, exigencia do AuraClient e se <code>/registrar</code>/<code>/entrar</code> estao liberados para membros.',
    'troubleshooting.modulesTitle': 'Modulo parece ativo, mas nao funciona',
    'troubleshooting.modulesText': 'Confira o modulo em <code>modules.enabled</code> e tambem a chave interna correspondente, como <code>clearLag.enabled</code>, <code>blockedItems.enabled</code> ou <code>autoPickup.enabled</code>. Depois execute <code>/aurasetup reload</code>.',
    'install.step1': 'Coloque o jar em plugins/.',
    'install.step2': 'Reinicie o servidor uma vez para gerar arquivos.',
    'install.step3': 'Edite plugins/AuraEssentials/config.yml, shop.yml e missions.yml quando quiser ajustar manualmente.',
    'install.step4': 'Use /aurasetup reload depois de alterar configs manualmente.',
    'install.opt1': 'Java: resource pack de glyphs pode ser enviado automaticamente.',
    'install.opt2': 'Bedrock: resource pack pode ser copiado para a pasta do Geyser.',
    'install.opt3': 'Discord: precisa de bot token e canal de controle se for usar bridge/vinculo.',
    'install.packRequired': 'O pack Java e obrigatorio por padrao; no Bedrock, o pack e forcado quando a integracao estiver habilitada.',
    'install.title': 'Servidor recomendado',
    'install.optional': 'Dependencias opcionais',
    'install.desc': 'Use Paper, Purpur ou Pufferfish na linha 1.21.9+. O plugin foi feito para rodar como plugin Bukkit/Paper normal, sem proxy obrigatorio.',
    'install.optionalDesc': 'Geyser/Floodgate sao softdepend. Se estiverem presentes, o menu Bedrock e forms administrativos ficam mais naturais para jogadores Bedrock.',
    'modules.item1': 'loja: compra, venda e catalogo',
    'modules.item2': 'missao: progresso e recompensas',
    'modules.item3': 'discord: vinculo e bridge',
    'modules.item4': 'terreno: claim de chunk',
    'modules.item5': 'protecao: regioes administrativas',
    'modules.item6': 'npc: NPCs do servidor',
    'modules.item7': 'holograma: textos flutuantes',
    'modules.item8': 'tpa: pedidos de teleporte',
    'modules.item9': 'back: voltar da morte',
    'modules.item10': 'login: senha e sessao',
    'modules.item11': 'skin: skin por nick',
    'modules.item12': 'clearlag: limpeza de drops',
    'modules.item13': 'autopickup: drops para inventario',
    'modules.item14': 'border: world border global',
    'modules.item15': 'blocked_items: itens proibidos',
    'modules.item16': 'combatlog: bloqueio em combate',
    'modules.item17': 'duelo: PvP combinado',
    'modules.item18': 'pvp_state: PvP pessoal',
    'modules.item19': 'cla: sistema de clans',
    'modules.item20': 'vip_cargo: VIPs e cargos',
    'modules.item21': 'warp: warps do servidor',
    'modules.item22': 'rtp: teleporte aleatorio',
    'modules.item23': 'sethome: homes',
    'modules.item24': 'kit: kit inicial',
    'modules.item25': 'regras: texto de regras',
    'modules.item26': 'ajuda: texto de ajuda',
    'modules.item27': 'saldo_pix: economia e pix',
    'modules.item28': 'graveto: captura de mobs',
    'modules.item29': 'vanish: staff invisivel',
    'modules.item30': 'lojas de jogadores e placas',
    'modules.item31': 'chat local, global e Bedrock',
    'modules.item32': 'crates, chaves e premios',
    'modules.item33': 'chaves por tempo jogado',
    'modules.item34': 'spawn e retorno do lobby',
    'modules.item35': 'apelido visual, tab e nametag',
    'extra.cratesTitle': 'Caixas e chaves fisicas',
    'extra.cratesText': 'O sistema de crates sorteia premios configurados por caixa. Admin define local, chave, premios, preview, animacao e efeitos.',
    'extra.timerKeysTitle': 'Chaves por tempo jogado',
    'extra.timerKeysText': 'Jogadores acumulam chaves conforme o tempo jogado e o cargo. O sistema usa o modulo <code>keys_timer</code> e a tela <code>/chaves</code>.',
    'extra.timerKeysConfig': 'A entrega depende das configuracoes de tempo/cargo e pode ser consultada na tela de chaves.',
    'extra.chatTitle': 'Chat local e global',
    'extra.chatText': 'O chat local usa raio e mundo; o global pode ter bloqueio para membros, permissao e cooldown. Bedrock pode receber chat Vanilla.',
    'extra.playerShopTitle': 'Loja de jogador',
    'extra.playerShopText': 'Alem da loja global, jogadores podem criar lojas de bau e placas quando <code>shop_chest</code> estiver ativo.',
    'extra.lobbyTitle': 'Lobby e spawn',
    'extra.lobbyText': 'Controla <code>/spawn</code>, retorno ao entrar, posicao de lobby e salvamento do local anterior.',
    'extra.auctionTitle': 'Leilao',
    'extra.auctionText': 'Leilao simples entre jogadores com aliases <code>/auction</code>, <code>/leilao</code> e <code>/ah</code>.',
    'extra.maintenanceTitle': 'Manutencao e proxy portal',
    'extra.maintenanceText': 'A manutencao redireciona jogadores pelo proxy. O bypass administrativo usa uma permissao separada e o destino depende da configuracao do proxy.',
    'extra.proxyPortalTitle': 'Proxy Portal',
    'extra.proxyPortalText': 'O sistema cria rotas de transferencia usando regioes cubicas marcadas manualmente ou uma rota por raio baseada no bloco de portal Nether Vanilla mais proximo. Nao existe deteccao automatica de qualquer portal sem configurar uma rota.',
    'extra.proxyPortalBehavior': 'No modo <code>area</code>, voce marca dois cantos e o plugin converte a regiao em blocos de construcao/efeitos. No modo <code>raio</code>, ele procura o portal Nether Vanilla mais proximo na hora de salvar a rota; durante o uso, a entrada precisa tocar um portal Vanilla dentro do raio configurado.',
    'extra.endTitle': 'Controles do End',
    'extra.endText': 'O End possui teleporte configuravel, protecao contra dano do dragao, destino fixo e protecao da ilha principal. Esses controles nao sao um modulo separado na grade, mas fazem parte do plugin.',
    'extra.extensionsTitle': 'Extensoes distribuidas separadamente',
    'extra.extensionsText': 'O workspace tambem contem extensoes que nao sao modulos internos do jar principal: Aura AntiCheat, Chat Game e Guerra de Reinos Bridge. Elas dependem da API de extensoes do AuraEssentials.',
    'extra.extensionsStatus': 'Aura AntiCheat e Chat Game sao extensoes ativas; a extensao Guerra de Reinos esta preparada para debug e envio futuro, mas o README informa que ainda nao tem conexao real com backend.',
    'modules.cmd': '/aurasetup status, /aurasetup toggle loja, /aurasetup enable discord, /aurasetup disable combatlog, /aurasetup reload'
  },
  en: {
    'brand.rocha': 'Rocha',
    'brand.project': 'Project',
    'nav.home': 'Home',
    'nav.projects': 'Projects',
    'nav.downloads': 'Downloads',
    'nav.wiki': 'Wiki',
    'nav.community': 'Community',
    'account.login': 'Login',
    'hero.eyebrow': 'Rocha Project Wiki',
    'hero.title': 'Project documentation',
    'hero.subtitle': 'Choose a project to open the manual. The idea is to stay fast: no wall of text at the very beginning.',
    'content.manualTitle': 'Plugin manual',
    'content.manualText': 'Sections stay collapsed so the page does not become a wall of text. Use the sidebar or open it with the + icon.',
    'section.install': 'Installation',
    'section.permissions': 'Base permissions',
    'section.panel': 'Server web panel',
    'section.modules': 'Available modules',
    'section.extraSystems': 'Additional systems',
    'section.commands': 'Complete command reference',
    'section.login': 'Login and AuraClient',
    'section.discord': 'Discord',
    'section.shop': 'Shop',
    'section.missions': 'Missions',
    'section.vip': 'VIP and ranks',
    'section.prefix': 'Visual prefix and glyphs',
    'section.npc': 'NPC',
    'section.hologram': 'Floating text',
    'section.cla': 'Clan',
    'section.claim': 'Claim',
    'section.protection': 'Protection',
    'section.rules': 'Rules and help',
    'section.teleport': 'Teleport',
    'section.pvp': 'PvP, duel and combat log',
    'section.border': 'Border and blockers',
    'section.utilities': 'Utilities',
    'section.troubleshooting': 'Common issues',
    'sidebar.allWikis': 'All wikis',
    'sidebar.project': 'AuraEssentials',
    'project.plugin': 'Plugin',
    'project.launcher': 'Launcher',
    'project.client': 'Client',
    'project.pluginDesc': 'Installation, web panel, modules, commands and configuration.',
    'project.launcherDesc': 'Java/Bedrock launcher, sessions and downloads.',
    'project.clientDesc': 'Client, mod, cosmetics and server integration.',
    'install.serverTitle': 'Recommended server',
    'install.serverText': 'Use Paper, Purpur or Pufferfish on 1.21.9+. The plugin was designed to run as a normal Bukkit/Paper plugin without requiring a proxy.',
    'install.optTitle': 'Optional dependencies',
    'install.optText': 'Geyser/Floodgate are soft dependencies. When present, the Bedrock menu and admin forms feel more natural for Bedrock players.',
    'install.tip': 'The plugin is designed to run as a standard Bukkit/Paper plugin without requiring a proxy.',
    'install.step1': 'Place the jar in plugins/.',
    'install.step2': 'Restart the server once to generate its files.',
    'install.step3': 'Edit plugins/AuraEssentials/config.yml, shop.yml and missions.yml when you need manual adjustments.',
    'install.step4': 'Run /aurasetup reload after manually editing configuration files.',
    'install.opt1': 'Java: the glyph resource pack can be sent automatically.',
    'install.opt2': 'Bedrock: the resource pack can be copied to the Geyser folder.',
    'install.opt3': 'Discord: a bot token and control channel are required for bridge/linking.',
    'install.packRequired': 'The Java pack is required by default; on Bedrock, the pack is forced when the integration is enabled.',
    'install.title': 'Recommended server',
    'install.optional': 'Optional dependencies',
    'install.desc': 'Use Paper, Purpur or Pufferfish on 1.21.9+. The plugin runs as a normal Bukkit/Paper plugin without requiring a proxy.',
    'install.optionalDesc': 'Geyser/Floodgate are soft dependencies. When present, the Bedrock menu and admin forms feel more natural for Bedrock players.',
    'panel.title': 'Server web panel',
    'panel.text': 'The web panel edits a safe draft. Nothing is applied to the server until an admin confirms it in-game.',
    'panel.explain': 'The web panel edits a safe draft. Nothing is applied to the server until an admin confirms it in-game.',
    'panel.afterLink': 'After linking the server to your Rocha account, it appears in Profile > Aura Server. The temporary link expires in about 30 minutes.',
    'panel.security': 'The session is created for administrators only. The plugin sends a snapshot, the site saves a draft, and the server applies it only after <code>/aurapanel apply</code>.',
    'panel.step1': 'Generate the session',
    'panel.step2': 'Edit on the site',
    'panel.step3': 'Save the draft',
    'panel.step4': 'Confirm in-game',
    'permissions.explain': 'Complete list of plugin permissions for administration, login, land, teleport, VIP, moderation and server utilities.',
    'permissions.admin': 'Manages the plugin, opens the panel, changes systems, NPCs, holograms, economy, roles and the server. (default: OP)',
    'permissions.rapidLogin': 'Allows /rapidlogin to authenticate a player quickly. (default: OP)',
    'permissions.graveto': 'Allows receiving the capture wand with /mobstick. (default: everyone)',
    'permissions.gravetoUse': 'Allows using the capture wand on released mobs. (default: everyone)',
    'permissions.terreno': 'Allows using /claim; the server may still require VIP. (default: everyone)',
    'permissions.vincular': 'Allows using /link to connect Discord. (default: everyone)',
    'permissions.autopickup': 'Allows toggling personal AutoPickup. (default: everyone)',
    'permissions.cla': 'Allows using the clan system. (default: everyone)',
    'permissions.rtp': 'Allows /rtp. (default: everyone)',
    'permissions.rtpBypass': 'Bypasses RTP cooldown. (default: OP)',
    'permissions.inspect': 'Allows /invsee and /endersee. (default: OP)',
    'permissions.vanish': 'Allows /vanish. (default: OP)',
    'permissions.vanishSee': 'Allows seeing vanished players. (default: OP)',
    'permissions.claCreate': 'Allows creating a clan. (default: everyone)',
    'permissions.servers': 'Allows opening the server transfer list. (default: everyone)',
    'permissions.auction': 'Allows using the player auction. (default: everyone)',
    'permissions.fly': 'Allows using /fly. (default: OP)',
    'permissions.gamemode': 'Allows using /gamemode. (default: OP)',
    'permissions.setspawn': 'Allows setting the lobby spawn. (default: OP)',
    'permissions.timefreeze': 'Allows using /freeze. (default: OP)',
    'permissions.proxyportal': 'Allows creating and removing custom proxy portals. (default: OP)',
    'permissions.caixaAdmin': 'Allows administering crates and keys. (default: OP)',
    'permissions.maintenanceAdmin': 'Allows administering maintenance mode. (default: OP)',
    'permissions.maintenanceBypass': 'Bypasses maintenance-mode redirection. (default: OP)',
    'permissions.nick': 'Allows using /changenick without VIP. (default: nobody)',
    'permissions.chatGlobal': 'Allows using /global when global chat is blocked for members. (default: OP)',
    'permissions.chatGlobalBypass': 'Bypasses global chat block and cooldown. (default: OP)',
    'permissions.shopChestCreate': 'Allows creating chest shops. (default: everyone)',
    'permissions.shopChestUse': 'Allows buying and selling in chest shops. (default: everyone)',
    'permissions.shopChestAdmin': 'Allows protecting and removing chest shops. (default: OP)',
    'modules.title': 'Available modules',
    'modules.text': 'Each module can be enabled or disabled in modules.enabled, from the panel in Configure, or with /aurasetup toggle <module>.',
    'modules.explain': 'Each module can be enabled or disabled in modules.enabled, from the panel in Configure, or with /aurasetup toggle <module>.',
    'modules.item1': 'shop: buying, selling and catalog',
    'modules.item2': 'mission: progression and rewards',
    'modules.item3': 'discord: linking and bridge',
    'modules.item4': 'territory: chunk claim',
    'modules.item5': 'protection: administrative regions',
    'modules.item6': 'npc: server NPCs',
    'modules.item7': 'hologram: floating text',
    'modules.item8': 'tpa: teleport requests',
    'modules.item9': 'back: return from death',
    'modules.item10': 'login: password and session',
    'modules.item11': 'skin: skin by nickname',
    'modules.item12': 'clearlag: drop cleanup',
    'modules.item13': 'autopickup: drops to inventory',
    'modules.item14': 'border: global world border',
    'modules.item15': 'blocked_items: blocked items',
    'modules.item16': 'combatlog: combat blocking',
    'modules.item17': 'duel: combined PvP',
    'modules.item18': 'pvp_state: personal PvP',
    'modules.item19': 'clan: clan system',
    'modules.item20': 'vip_cargo: VIPs and roles',
    'modules.item21': 'warp: server warps',
    'modules.item22': 'rtp: random teleport',
    'modules.item23': 'sethome: homes',
    'modules.item24': 'kit: starter kit',
    'modules.item25': 'rules: rules text',
    'modules.item26': 'help: help text',
    'modules.item27': 'saldo_pix: economy and pix',
    'modules.item28': 'graveto: mob capture',
    'modules.item29': 'vanish: invisible staff',
    'modules.item30': 'player shops and signs',
    'modules.item31': 'local, global and Bedrock chat',
    'modules.item32': 'crates, keys and rewards',
    'modules.item33': 'playtime keys',
    'modules.item34': 'lobby spawn and return',
    'modules.item35': 'visual nickname, tab and nametag',
    'extra.cratesTitle': 'Crates and physical keys',
    'extra.cratesText': 'The crate system rolls configured rewards per crate. Admins define locations, keys, rewards, preview, animation and effects.',
    'extra.timerKeysTitle': 'Playtime keys',
    'extra.timerKeysText': 'Players earn keys according to playtime and rank. The system uses the <code>keys_timer</code> module and the <code>/keys</code> screen.',
    'extra.timerKeysConfig': 'Delivery depends on time/rank settings and can be checked in the keys screen.',
    'extra.chatTitle': 'Local and global chat',
    'extra.chatText': 'Local chat uses radius and world; global chat can have member blocking, permission and cooldown. Bedrock can receive Vanilla chat.',
    'extra.playerShopTitle': 'Player shops',
    'extra.playerShopText': 'Besides the global shop, players can create chest shops and signs when <code>shop_chest</code> is enabled.',
    'extra.lobbyTitle': 'Lobby and spawn',
    'extra.lobbyText': 'Controls <code>/spawn</code>, return on join, lobby position and saving the previous location.',
    'extra.auctionTitle': 'Auction',
    'extra.auctionText': 'Simple player auction with aliases <code>/auction</code>, <code>/leilao</code> and <code>/ah</code>.',
    'extra.maintenanceTitle': 'Maintenance and proxy portal',
    'extra.maintenanceText': 'Maintenance redirects players through the proxy. Administrative bypass uses a separate permission and the destination depends on proxy configuration.',
    'extra.proxyPortalTitle': 'Proxy Portal',
    'extra.proxyPortalText': 'The system creates transfer routes using manually marked cuboid regions or a radius route based on the nearest Vanilla Nether portal block. It does not automatically detect every portal without a configured route.',
    'extra.proxyPortalBehavior': 'In <code>area</code> mode, you mark two corners and the plugin converts the region into construction/effect blocks. In <code>radius</code> mode, it searches for the nearest Vanilla Nether portal when saving the route; during use, entry must touch a Vanilla portal within the configured radius.',
    'extra.endTitle': 'End controls',
    'extra.endText': 'The End has configurable teleport, dragon-damage protection, a fixed destination and main-island protection. These controls are not a separate grid module but are part of the plugin.',
    'extra.extensionsTitle': 'Separately packaged extensions',
    'extra.extensionsText': 'The workspace also contains extensions that are not internal modules of the main jar: Aura AntiCheat, Chat Game and Guerra de Reinos Bridge. They depend on the AuraEssentials extension API.',
    'extra.extensionsStatus': 'Aura AntiCheat and Chat Game are active extensions; the Guerra de Reinos extension is prepared for debug and future sending, but its README states that it has no real backend connection yet.',
    'login.title': 'Login and AuraClient',
    'login.text': 'Local registration system for mixed offline/online servers with password, password change, session control and anti-multicount protection.',
    'login.explain': 'Local registration system for mixed offline/online servers with password, password change, session control and anti-multicount protection.',
    'login.config': 'Main settings: <code>enableIpTrust</code>, <code>trustedDurationSeconds</code>, <code>multiAccount</code>, <code>modGate.requireAuraClient</code>, <code>authRouting</code> and Java/Bedrock packs.',
    'login.registrar': 'Creates the player password.',
    'login.entrar': 'Authenticates the current session.',
    'login.mudarsenha': 'Changes the account password.',
    'login.rapidlogin': 'Admin authenticates a player manually.',
    'login.multiconta': 'Admin controls the account limit per IP.',
    'discord.title': 'Discord',
    'discord.text': 'Integrates account linking, bridge and Discord enforcement. The bot token stays on the server, never on the public site.',
    'discord.explain': 'Integrates account linking, bridge and Discord enforcement. The bot token stays on the server, never on the public site.',
    'discord.config': 'Important fields: <code>discordLink.botToken</code>, <code>controlChannelId</code>, <code>forceOnJoin</code>, <code>requiredAfterHours</code> and <code>useOriginalServerText</code>.',
    'discord.vincular': 'Generates a code to link Minecraft to Discord.',
    'discord.vincularCodigo': 'Consumes the code received through the bot flow.',
    'discord.desvincular': 'Admin removes a player link.',
    'discord.channels': 'Use <code>chatChannelId</code> for the public bridge channel and <code>controlChannelId</code> for the private bot-control channel. <code>forceOnJoin</code> and <code>requiredAfterHoursEnabled</code> can require linking at login.',
    'shop.title': 'Shop',
    'shop.text': 'Buying and selling menu with categories, products, Minecraft item icons, purchase value, sale value and configurable currency.',
    'shop.explain': 'Buying and selling menu with categories, products, Minecraft item icons, purchase value, sale value and configurable currency.',
    'shop.file': 'Main file: <code>shop.yml</code>. In the panel, use Shop > Catalog to review and Shop > Edit products to add or remove items.',
    'shop.abre': 'Opens the shop.',
    'shop.comando': 'Uses the shop by command when the GUI is not ideal.',
    'shop.admin': 'Administers shop values by command.',
    'shop.sellOptions': 'Sells a quantity or everything when using the <code>all</code> argument.',
    'shop.englishAliases': 'English aliases accepted by the shop executor.',
    'missions.title': 'Missions',
    'missions.text': 'Mission system with categories and goals such as killing mobs, mining blocks or harvesting plants. A player activates a mission, progresses and can cancel it.',
    'missions.explain': 'Mission system with categories and goals such as killing mobs, mining blocks or harvesting plants. A player activates a mission, progresses and can cancel it.',
    'missions.file': 'Main file: <code>missions.yml</code>. Settings: <code>missions.autosaveSeconds</code> and <code>missions.repeatCooldownSeconds</code>.',
    'missions.abre': 'Opens the missions menu.',
    'missions.ativar': 'Activates a mission by ID.',
    'missions.listar': 'Lists loaded missions.',
    'missions.cancelar': 'Cancels the active mission and removes its progress.',
    'missions.categories': 'Current categories include <code>mining</code> and <code>farming</code>; use <code>/quest activate</code> and <code>/quest list</code> as English aliases.',
    'vip.title': 'VIP and roles',
    'vip.text': 'Controls VIPs, visual roles, activation keys, VIP kits and utilities such as chest, crafting, anvil and leaderboard.',
    'vip.explain': 'Controls VIPs, visual roles, activation keys, VIP kits and utilities such as chest, crafting, anvil and leaderboard.',
    'vip.config': 'In the panel, VIPs can have items, quantity, lore, custom names, glow, unbreakable status and Vanilla/NBT enchantments.',
    'vip.setvip': 'Sets or removes VIP.',
    'vip.entregarcargo': 'Sets a special visual rank.',
    'vip.gerarchave': 'Creates a one-time-use key.',
    'vip.chave': 'Activates a VIP key.',
    'vip.kitvip': 'Delivers the VIP kit.',
    'vip.resetkitvip': 'Resets the VIP kit usage.',
    'vip.behavior': 'The VIP kit is single-use per VIP when <code>vipKit.singleUsePerVip</code> is enabled; <code>/resetvipkit</code> allows another use.',
    'prefix.title': 'Visual prefix and glyphs',
    'prefix.text': 'The plugin separates chat visual formatting, nametag and tab list styling. Glyphs depend on the Java/Bedrock resource pack to render correctly.',
    'prefix.explain': 'The plugin separates chat visual formatting, nametag and tab list styling. Glyphs depend on the Java/Bedrock resource pack to render correctly.',
    'prefix.help': 'Use Minecraft codes like <code>&amp;6&amp;l</code> in fields that accept formatted text. The panel shows a basic preview rendering.',
    'prefix.chatMessage': '<code>chat_message</code>: chat message format.',
    'prefix.nametagPlayer': '<code>nametag_player</code>: text above the player head.',
    'prefix.tablist': '<code>tablist</code>: visual in the player list.',
    'npc.title': 'NPC',
    'npc.text': 'Server NPCs with skin, title, description, action and position. They can open a menu, TPA, shop, missions or execute a configured command.',
    'npc.explain': 'Server NPCs with skin, title, description, action and position. They can open a menu, TPA, shop, missions or execute a configured command.',
    'npc.config': 'Global config: <code>npc.renderDistanceChunks</code> and <code>npc.hologramOffsetY</code>.',
    'npc.currentConfig': 'Current values: renders within 1 chunk and uses a hologram offset of 2.05. Named skins are stored in <code>npc_visuals.yml</code>.',
    'hologram.title': 'Floating text',
    'hologram.text': 'Simple holograms for warnings, lobbies, shops and server areas.',
    'hologram.explain': 'Simple holograms for warnings, lobbies, shops and server areas.',
    'hologram.config': 'Global config: <code>holograma.renderDistanceChunks</code>, <code>backgroundEnabled</code> and <code>lineWidth</code>.',
    'hologram.currentConfig': 'Current values: renders within 1 chunk, background enabled and line width 220.',
    'cla.title': 'Clan',
    'cla.text': 'Player group system with tag, name, description, color, members, co-owners, base, warps, bank, chat, alliances and internal PvP.',
    'cla.explain': 'Player group system with tag, name, description, color, members, co-owners, base, warps, bank, chat, alliances and internal PvP.',
    'cla.config': 'Main config: tag/name size, max members, warps, bank, alliances, internal PvP and auto-delete when only the owner remains.',
    'cla.currentConfig': 'Current values: tag 2-5 characters, name 3-16, description up to 60, 10 members, 2 co-owners, 1 warp, 300s invite duration and auto-delete after 10h with only the owner. Alliances, friendly PvP, Ender Chest, extra warp, roles and bank are enabled.',
    'claim.title': 'Claim',
    'claim.text': '16x16 chunk claim. The player takes a claim wand and registers the chunk by clicking a block. By default it may require VIP.',
    'claim.explain': '16x16 chunk claim. The player takes a claim wand and registers the chunk by clicking a block. By default it may require VIP.',
    'claim.currentConfig': 'Current config: VIP is required; limit is 4096 blocks for members, 16384 for VIP and 262144 for admins. The VIP limit is separate from the normal limit.',
    'claim.pega': 'Gets the claim wand.',
    'claim.permitir': 'Authorizes another player on the claim.',
    'claim.remover': 'Removes permission.',
    'claim.listar': 'Shows claims.',
    'claim.ver': 'Shows the border of the current chunk.',
    'claim.deletar': 'Removes a claim you own or another one as admin.',
    'protection.title': 'Protection',
    'protection.text': 'Administrative areas defined by selecting two positions. Useful for spawn, shops, arenas and special regions.',
    'protection.explain': 'Administrative areas defined by selecting two positions. Useful for spawn, shops, arenas and special regions.',
    'protection.flags': 'Accepted flags include break, place, interact, buckets, entry, monsters, pvp, entity_damage and explosions. The area can be created with two positions and managed through the panel or command.',
    'rules.title': 'Rules and help',
    'rules.text': 'Two simple text screens to guide players on the server. They support Minecraft color codes and wiki links.',
    'rules.explain': 'Two simple text screens to guide players on the server. They support Minecraft color codes and wiki links.',
    'rules.config': 'Main fields: <code>texts.regrasTitle</code>, <code>texts.regras</code>, <code>texts.regrasWikiUrl</code>, <code>texts.ajudaTitle</code>, <code>texts.ajuda</code> and <code>texts.ajudaWikiUrl</code>.',
    'rules.regras': 'Shows the title, rule lines and configured link.',
    'rules.ajuda': 'Shows the basic commands, login instructions and configured link.',
    'utilities.menuMain': 'Main Bedrock/Geyser menu.',
    'utilities.menuAdmin': 'Bedrock admin menu.',
    'utilities.kit': 'Initial kit with single use.',
    'utilities.saldo': 'Shows the balance.',
    'utilities.dinheiro': 'Admin changes the balance.',
    'utilities.pix': 'Transfers coins.',
    'utilities.clearlag': 'Clears configured drops.',
    'utilities.graveto': 'Receives the allowed mob-capture item.',
    'utilities.autopickup': 'Controls automatic pickup.',
    'utilities.skin': 'Sets the official skin by nickname.',
    'utilities.vanish': 'Staff invisibility.',
    'utilities.inspect': 'Inventory and ender chest inspection.',
    'utilities.currentConfig': 'AutoPickup is enabled by default for blocks, mobs and fishing; players can toggle it and receive an inventory-full warning. ClearLag runs every 600s, removes drops at least 30s old, ignores custom-named items and warns at 60s and 5s.',
    'teleport.title': 'Teleport',
    'teleport.text': 'TPA, back, warps, homes and RTP with cooldowns, dimension protection and safe radius checks.',
    'teleport.tpaTitle': 'TPA and Back',
    'teleport.tpaText': '<code>/tpa &lt;player&gt;</code>, <code>/aceitar &lt;player&gt;</code>, <code>/negar &lt;player&gt;</code> and <code>/back</code>. Can be blocked by dimension.',
    'teleport.warpTitle': 'Warp, Home and RTP',
    'teleport.warpText': '<code>/setwarp</code>, <code>/warp</code>, <code>/sethome</code>, <code>/home</code>, <code>/delhome</code> and <code>/rtp</code>. RTP respects radius, cooldown, world border and water/lava.',
    'teleport.currentConfig': 'Current config: RTP has a 300s cooldown, 3s warmup, radius from 250 to 5000, up to 24 attempts and is enabled only in the Overworld by default. TPA and Back are enabled in the Overworld, Nether and End.',
    'pvp.title': 'PvP, duel and combat log',
    'pvp.text': 'Custom PvP system, duels and combat log with exit protection and combat blocking.',
    'pvp.explain': 'Custom PvP system, duels and combat log with exit protection and combat blocking.',
    'pvp.config': 'CombatLog can block warp, tpa, rtp, home and back during combat. It can also kill the player on logout if configured.',
    'pvp.status': 'Player changes personal PvP state.',
    'pvp.admin': 'Admin controls PvP by dimension.',
    'pvp.duelo': 'Creates a temporary PvP duel arena.',
    'pvp.currentConfig': 'Current config: combat lasts 8s; blocks warp, TPA, RTP, home, back and clan base; shows an action bar and does not kill on quit by default. Duels support all three dimensions, with a 30s request timeout, 45s ready timeout and 3s countdown.',
    'border.title': 'Border and blockers',
    'border.text': 'Global world border system and list of blocked items by module or panel.',
    'border.globalTitle': 'Global Border',
    'border.globalText': 'Defines the size and center of the world border for Overworld, Nether and End. It can be enabled by the <code>border</code> module.',
    'border.globalCommand': 'Quick command: <code>/setborder &lt;size&gt;</code> uses your current position as the center in the world you are standing in.',
    'border.blockedTitle': 'Blocked Items',
    'border.blockedText': 'Removes prohibited materials from the inventory and can check the Ender Chest. Configure it in <code>blockedItems.materials</code> or from the panel under Blocked Items.',
    'border.blockedTip': 'Use it to block command blocks, bedrock, barriers or any material that should not circulate.',
    'border.currentConfig': 'By default, the border and blocked-items modules start disabled. Initial borders are 8000 in the Overworld, 5000 in the Nether and 12000 in the End; blocked items also scan Ender Chests when enabled.',
    'utilities.title': 'Utilities',
    'utilities.text': 'Menu, kits, balance, pix, clearlag, grappling stick, auto-pickup, skin, vanish and inspection tools.',
    'utilities.explain': 'Menu, kits, balance, pix, clearlag, grappling stick, auto-pickup, skin, vanish and inspection tools for everyday gameplay.',
    'troubleshooting.title': 'Common issues',
    'troubleshooting.text': 'Quick checklist for the most frequent issues with glyphs, commands, panel and login.',
    'troubleshooting.explain': 'Quick checklist for the most frequent issues with glyphs, commands, panel and login.',
    'troubleshooting.glyphsTitle': 'Glyphs appear square or tiny',
    'troubleshooting.glyphsText': 'The player did not load the correct resource pack. Check <code>javaResourcePack</code>, <code>bedrockResourcePack</code> and whether the server requires the pack.',
    'troubleshooting.commandTitle': 'Command does not appear in the tab list',
    'troubleshooting.commandText': 'Check whether the module is enabled in <code>modules.enabled</code> or in the Configure panel. Then run <code>/aurasetup reload</code> and ask the player to relog if necessary.',
    'troubleshooting.siteTitle': 'I changed something on the site and it did not change on the server',
    'troubleshooting.siteText': 'Saving on the site creates a draft. Join the server and run <code>/aurapainel alteracoes</code> and then <code>/aurapainel aplicar</code>.',
    'troubleshooting.discordTitle': 'Discord sends messages to Discord but not back',
    'troubleshooting.discordText': 'Review <code>discordLink.botToken</code>, <code>controlChannelId</code>, permissions on the channel and whether the Discord module is active.',
    'troubleshooting.loginTitle': 'Player cannot log in',
    'troubleshooting.loginText': 'Check Login, Multiconta, AuthRouting, the AuraClient requirement and whether <code>/registrar</code>/<code>/entrar</code> are unlocked for members.',
    'troubleshooting.modulesTitle': 'A module seems enabled but does not work',
    'troubleshooting.modulesText': 'Check the module in <code>modules.enabled</code> and its matching internal setting, such as <code>clearLag.enabled</code>, <code>blockedItems.enabled</code> or <code>autoPickup.enabled</code>. Then run <code>/aurasetup reload</code>.'
  }
};

window.WIKI_COMMANDS = {
  pt: {
    menuadmin: 'menuadmin', setvip: 'setvip', set: 'set', entregarcargo: 'entregarcargo',
    criarcargo: 'criarcargo', npc: 'npc', holograma: 'holograma', expirarvip: 'expirarvip',
    gerarchave: 'gerarchave', chave: 'chave', chaves: 'chaves', kitvip: 'kitvip',
    resetkitvip: 'resetkitvip', tpa: 'tpa', aceitar: 'aceitar', negar: 'negar', tpahere: 'tpahere',
    duelo: 'duelo', setwarp: 'setwarp', delwarp: 'delwarp', warp: 'warp', warps: 'warps', rtp: 'rtp',
    sethome: 'sethome', home: 'home', homes: 'homes', delhome: 'delhome', back: 'back', spawn: 'spawn',
    setspawn: 'setspawn', gm: 'gm', registrar: 'registrar', entrar: 'entrar', mudarsenha: 'mudarsenha',
    mudarnick: 'mudarnick', textura: 'textura', rapidologin: 'rapidologin', multiconta: 'multiconta',
    desativar: 'desativar', pvp: 'pvp', setborder: 'setborder', kit: 'kit', kits: 'kits', missao: 'missao',
    cancelar: 'cancelar', aurasetup: 'aurasetup', aurapainel: 'aurapainel', servers: 'servers',
    manutencao: 'manutencao', proxyportal: 'proxyportal', caixa: 'caixa', auction: 'auction', regras: 'regras',
    ajuda: 'ajuda', fly: 'fly', congelar: 'congelar', menu: 'menu', loja: 'loja', playerloja: 'playerloja',
    shopadmin: 'shopadmin', bau: 'bau', verinv: 'verinv', verender: 'verender', topo: 'topo', craft: 'craft',
    bigorna: 'bigorna', saldo: 'saldo', dinheiro: 'dinheiro', enviarpix: 'enviarpix', clearlag: 'clearlag',
    graveto: 'graveto', g: 'g', l: 'l', tell: 'tell', leilao: 'leilao', auction: 'auction', ah: 'ah',
    cla: 'cla', clachat: 'clachat', terreno: 'terreno', protecao: 'protecao', vanish: 'vanish',
    autopickup: 'autopickup', ap: 'ap', vincular: 'vincular', desvincular: 'desvincular', skin: 'skin',
    warplist: 'warplist', lojaadmin: 'lojaadmin', setchave: 'setchave', setrank: 'setrank',
  },
  en: {
    menuadmin: 'adminmenu', setvip: 'vipset', set: 'set', entregarcargo: 'setrank',
    criarcargo: 'createrank', npc: 'npc', holograma: 'hologram', expirarvip: 'expirevip',
    gerarchave: 'generatekey', chave: 'redeemkey', chaves: 'keys', kitvip: 'kitvip',
    resetkitvip: 'resetvipkit', tpa: 'tpa', aceitar: 'tpaccept', negar: 'tpadeny', tpahere: 'tpahere',
    duelo: 'duel', setwarp: 'setwarp', delwarp: 'deletewarp', warp: 'warp', warps: 'warplist', rtp: 'rtp',
    sethome: 'sethome', home: 'home', homes: 'homes', delhome: 'delhome', back: 'back', spawn: 'lobby',
    setspawn: 'setspawn', gm: 'gamemode', registrar: 'register', entrar: 'login', mudarsenha: 'changepassword',
    mudarnick: 'changenick', textura: 'texture', rapidologin: 'quicklogin', multiconta: 'multiaccount',
    desativar: 'disable', pvp: 'pvp', setborder: 'setborder', kit: 'kit', kits: 'kitmenu', missao: 'quest',
    cancelar: 'cancel', aurasetup: 'aurasetup', aurapainel: 'aurapanel', servers: 'serverlist',
    manutencao: 'maintenance', proxyportal: 'portalproxy', caixa: 'crate', auction: 'auction', regras: 'rules',
    ajuda: 'help', fly: 'fly', congelar: 'freeze', menu: 'menu', loja: 'shop', playerloja: 'playerloja',
    shopadmin: 'shopadmin', bau: 'enderchest', verinv: 'invsee', verender: 'endersee', topo: 'top', craft: 'craft',
    bigorna: 'anvil', saldo: 'balance', dinheiro: 'moneyadmin', enviarpix: 'pay', clearlag: 'clearlag',
    graveto: 'mobstick', g: 'global', l: 'local', tell: 'tell', leilao: 'auction', auction: 'auction', ah: 'ah',
    cla: 'clan', clachat: 'clachat', terreno: 'claim', protecao: 'protection', vanish: 'vanish',
    autopickup: 'autopickup', ap: 'ap', vincular: 'link', desvincular: 'unlink', skin: 'skin',
    warplist: 'warplist', lojaadmin: 'shopadmin', setchave: 'setkey', setrank: 'setrank',
  }
};

window.WIKI_COMMAND_TOKENS = {
  pt: {
    criar: 'criar', info: 'info', membros: 'membros', ranking: 'ranking', aliados: 'aliados',
    aliar: 'aliar', aceitaralianca: 'aceitaralianca', removeralianca: 'removeralianca',
    convidar: 'convidar', aceitar: 'aceitar', sair: 'sair', deletar: 'deletar', base: 'base',
    enderchest: 'enderchest', setwarp: 'setwarp', warp: 'warp', removerwarp: 'removerwarp',
    banco: 'banco', guardar: 'guardar', retirar: 'retirar', chat: 'chat', perfil: 'perfil',
    retag: 'retag', renomear: 'renomear', descricao: 'descricao', cor: 'cor', pvp: 'pvp',
    cargo: 'cargo', expulsar: 'expulsar', ajuda: 'ajuda', ativar: 'ativar', listar: 'listar',
    cancelar: 'cancelar', comprar: 'comprar', vender: 'vender', remover: 'remover',
    definir: 'definir', definircompra: 'definircompra', definirvenda: 'definirvenda',
    recarregar: 'recarregar', adicionar: 'adicionar', permitir: 'permitir', ver: 'ver',
    deletararea: 'deletar', ferramenta: 'ferramenta', machado: 'machado', evento: 'evento',
    posicao: 'posicao', gerar: 'gerar', limpar: 'limpar', preview: 'preview',
    addpremio: 'addpremio', premio: 'premio', limparpremios: 'limparpremios', removerpremio: 'removerpremio',
    animacao: 'animacao', efeito: 'efeito', status: 'status', ligado: 'ligado', desligado: 'desligado',
    on: 'on', off: 'off', liberar: 'liberar', recarregar: 'recarregar', confirmar: 'confirmar',
    aplicar: 'aplicar', rejeitar: 'rejeitar', painel: 'painel', idioma: 'idioma', placar: 'placar',
    salvarnovato: 'salvarnovato', salvarvip: 'salvarvip', limparnovato: 'limparnovato', limparvip: 'limparvip',
    resetar: 'resetar', registrar: 'registrar', apaga: 'apagar', lobby: 'lobby', raio: 'raio',
    retorno: 'retorno', area: 'area', listarareas: 'listar', limpareas: 'limparareas', limpartudo: 'limpartudo',
    chave: 'chave', dar: 'dar', lista: 'lista', ativarvip: 'ativar', excluir: 'deletar',
    use: 'usar', status: 'status', nome: 'nome', jogador: 'jogador', cor: 'cor', valor: 'valor',
    membro: 'membro', subdono: 'subdono', mensagem: 'mensagem', senha: 'senha', categoria: 'categoria',
    modulo: 'modulo', dimensao: 'dimensao', tamanho: 'tamanho', codigo: 'codigo', tempo: 'tempo',
    mundo: 'mundo', texto: 'texto', nick: 'nick', tipo: 'tipo', novasenha: 'novaSenha', ligar: 'ligar', desligar: 'desligar', quest: 'quest', mineracao: 'mineracao',
    plantacao: 'plantacao', agora: 'agora', infinito: 'infinito', dono: 'dono', branco: 'branco',
    cinza: 'cinza', preto: 'preto', vermelho: 'vermelho', laranja: 'laranja', amarelo: 'amarelo',
    lima: 'lima', ciano: 'ciano', azul: 'azul', roxo: 'roxo', bronze: 'bronze', ouro: 'ouro',
    diamante: 'diamante', classica: 'classica', rapida: 'rapida', brilho: 'brilho', nenhum: 'nenhum',
    encanto: 'encanto', editar: 'editar', salvar: 'salvar', limpar: 'limpar', quebrar: 'quebrar',
    colocar: 'colocar', interagir: 'interagir', baldes: 'baldes', entrada: 'entrada', monstros: 'monstros',
    dano_entidade: 'dano_entidade', explosoes: 'explosoes', inventario: 'inventario', bau: 'bau',
    comandos: 'comandos', atalhomod: 'atalhomod', titulo: 'titulo', acao: 'acao', shop: 'shop',
    missoes: 'missoes', chaves: 'chaves', aqui: 'aqui', excluir: 'excluir', filtrar: 'filtrar',
    incluir: 'incluir', desfiltrar: 'desfiltrar', limparfiltro: 'limparfiltro', fundoseparado: 'fundoseparado',
    real: 'real', vanilla: 'vanilla', fillcmd: 'fillcmd', spawn: 'spawn', portal: 'portal',
    token: 'token', canal: 'canal', horas: 'horas', obrigar: 'obrigar', limpar: 'limpar'
  },
  en: {
    criar: 'create', info: 'info', membros: 'members', ranking: 'rank', aliados: 'allies',
    aliar: 'ally', aceitaralianca: 'acceptally', removeralianca: 'removeally', convidar: 'invite',
    aceitar: 'accept', sair: 'leave', deletar: 'delete', base: 'base', enderchest: 'enderchest',
    setwarp: 'setwarp', warp: 'warp', removerwarp: 'removewarp', banco: 'bank', guardar: 'deposit',
    retirar: 'withdraw', chat: 'chat', perfil: 'profile', retag: 'retag', renomear: 'rename',
    descricao: 'description', cor: 'color', pvp: 'pvp', cargo: 'role', expulsar: 'kick', ajuda: 'help',
    ativar: 'activate', listar: 'list', cancelar: 'cancel', comprar: 'buy', vender: 'sell', remover: 'remove',
    definir: 'set', definircompra: 'setbuy', definirvenda: 'setsell', recarregar: 'reload', adicionar: 'add',
    permitir: 'allow', ver: 'view', ferramenta: 'tool', machado: 'axe', evento: 'event', posicao: 'position',
    gerar: 'generate', limpar: 'clear', preview: 'preview', addpremio: 'addreward', premio: 'reward',
    limparpremios: 'clearrewards', removerpremio: 'removereward', animacao: 'animation', efeito: 'effect',
    status: 'status', ligado: 'enabled', desligado: 'disabled', ligar: 'on', desligar: 'off', on: 'on', off: 'off', aplicar: 'apply',
    rejeitar: 'reject', painel: 'panel', idioma: 'language', placar: 'scoreboard', salvarnovato: 'savenewbie',
    salvarvip: 'savevip', limparnovato: 'clearnewbie', limparvip: 'clearvip', resetar: 'reset', registrar: 'register',
    raio: 'radius', retorno: 'return', area: 'area', listarareas: 'list', limpareas: 'clearareas',
    limpartudo: 'clearall', chave: 'key', dar: 'give', lista: 'list', ativarvip: 'enable',
    confirmar: 'confirm', usar: 'use', liberar: 'allow', recarregar: 'reload', excluir: 'delete'
    ,nome: 'name', jogador: 'player', cor: 'color', valor: 'amount', membro: 'member', subdono: 'co-owner',
    mensagem: 'message', senha: 'password', categoria: 'category', modulo: 'module', dimensao: 'dimension',
    tamanho: 'size', codigo: 'code', tempo: 'time', mundo: 'world', texto: 'text', nick: 'nickname',
    tipo: 'type', novasenha: 'newPassword', quest: 'quest', mineracao: 'mining', plantacao: 'farming', agora: 'now', infinito: 'infinite',
    dono: 'owner', branco: 'white', cinza: 'gray', preto: 'black', vermelho: 'red', laranja: 'orange',
    amarelo: 'yellow', lima: 'lime', ciano: 'cyan', azul: 'blue', roxo: 'purple', bronze: 'bronze',
    ouro: 'gold', diamante: 'diamond', classica: 'classic', rapida: 'quick', brilho: 'shine', nenhum: 'none',
    encanto: 'enchant', editar: 'edit', salvar: 'save', quebrar: 'break', colocar: 'place', interagir: 'interact',
    baldes: 'buckets', entrada: 'entry', monstros: 'monsters', dano_entidade: 'entity_damage', explosoes: 'explosions',
    inventario: 'inventory', bau: 'container', comandos: 'commands', atalhomod: 'modshortcut', titulo: 'title',
    acao: 'action', shop: 'shop', missoes: 'missions', chaves: 'keys', aqui: 'here', excluir: 'exclude',
    filtrar: 'filter', incluir: 'include', desfiltrar: 'unfilter', limparfiltro: 'clearfilter', fundoseparado: 'splitbackground',
    real: 'real', vanilla: 'vanilla', fillcmd: 'fillcmd', spawn: 'spawn', portal: 'portal', token: 'token',
    canal: 'channel', horas: 'hours', obrigar: 'force', limpar: 'clear'
  }
};
